#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import readline from 'readline';
import chalk from 'chalk';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.join(__dirname, '..');

class SetupWizard {
  constructor() {
    this.rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout
    });
    this.config = {};
  }

  async question(prompt) {
    return new Promise((resolve) => {
      this.rl.question(prompt, resolve);
    });
  }

  async run() {
    console.log(chalk.cyan(`
🚀 ClickUp Automation Toolkit Setup Wizard
==========================================

This wizard will help you configure your ClickUp integration.
You'll need your ClickUp API credentials to continue.

Let's get started! 🎉
        `));

    try {
      await this.gatherCredentials();
      await this.createEnvFile();
      await this.testConnection();
      await this.showNextSteps();
    } catch (error) {
      console.error(chalk.red('❌ Setup failed:'), error.message);
      process.exit(1);
    } finally {
      this.rl.close();
    }
  }

  async gatherCredentials() {
    console.log(chalk.yellow('\n📋 Step 1: ClickUp API Credentials'));
    console.log(chalk.gray('Get your API key from: https://app.clickup.com/settings/apps\n'));

    // API Key
    let apiKey = '';
    while (!apiKey) {
      apiKey = await this.question('Enter your ClickUp API Key: ');
      if (!apiKey) {
        console.log(chalk.red('❌ API Key is required!'));
      }
    }
    this.config.CLICKUP_API_KEY = apiKey;

    // Team ID
    console.log(chalk.gray('\nYour Team ID can be found in your ClickUp URL or via API'));
    let teamId = '';
    while (!teamId) {
      teamId = await this.question('Enter your ClickUp Team ID: ');
      if (!teamId) {
        console.log(chalk.red('❌ Team ID is required!'));
      }
    }
    this.config.CLICKUP_TEAM_ID = teamId;

    // List ID
    console.log(chalk.gray('\nYour List ID can be found in the list URL or via API'));
    let listId = '';
    while (!listId) {
      listId = await this.question('Enter your default ClickUp List ID: ');
      if (!listId) {
        console.log(chalk.red('❌ List ID is required!'));
      }
    }
    this.config.CLICKUP_LIST_ID = listId;

    // Optional: Default Assignee
    console.log(chalk.gray('\nOptional: Default assignee for new tasks'));
    const assignee = await this.question('Enter default assignee User ID (optional, press Enter to skip): ');
    if (assignee) {
      this.config.CLICKUP_DEFAULT_ASSIGNEE = assignee;
    }

    console.log(chalk.green('\n✅ Credentials collected!'));
  }

  async createEnvFile() {
    console.log(chalk.yellow('\n📝 Step 2: Creating .env file'));

    const envPath = path.join(projectRoot, '.env');

    // Check if .env already exists
    if (fs.existsSync(envPath)) {
      const overwrite = await this.question(
        chalk.orange('⚠️  .env file already exists. Overwrite? (y/N): ')
      );
      if (overwrite.toLowerCase() !== 'y') {
        console.log(chalk.blue('📄 Keeping existing .env file'));
        return;
      }
    }

    // Create .env content
    let envContent = `# ClickUp API Configuration
# Generated by setup wizard on ${new Date().toISOString()}

CLICKUP_API_KEY=${this.config.CLICKUP_API_KEY}
CLICKUP_TEAM_ID=${this.config.CLICKUP_TEAM_ID}
CLICKUP_LIST_ID=${this.config.CLICKUP_LIST_ID}
`;

    if (this.config.CLICKUP_DEFAULT_ASSIGNEE) {
      envContent += `CLICKUP_DEFAULT_ASSIGNEE=${this.config.CLICKUP_DEFAULT_ASSIGNEE}\n`;
    }

    envContent += `
# Optional: Environment settings
NODE_ENV=production
DEBUG=false

# Optional: Notification settings
ENABLE_NOTIFICATIONS=true
`;

    try {
      fs.writeFileSync(envPath, envContent);
      console.log(chalk.green('✅ .env file created successfully!'));
    } catch (error) {
      throw new Error(`Failed to create .env file: ${error.message}`);
    }
  }

  async testConnection() {
    console.log(chalk.yellow('\n🔍 Step 3: Testing connection'));

    try {
      // Import and test the automation class
      const { default: ClickUpAutomation } = await import('../src/clickup-automation.js');

      console.log(chalk.blue('⏳ Connecting to ClickUp API...'));

      const automation = new ClickUpAutomation();
      const result = await automation.testConnection();

      if (result.success) {
        console.log(chalk.green('✅ Connection successful!'));
        console.log(chalk.cyan(`📊 Team: ${result.team.name}`));
        console.log(chalk.cyan(`👥 Members: ${result.team.members.length}`));
      } else {
        throw new Error('Connection test failed');
      }
    } catch (error) {
      console.log(chalk.red('❌ Connection test failed:'), error.message);
      console.log(chalk.yellow('💡 Please check your credentials and try again'));

      const retry = await this.question('Would you like to retry with different credentials? (y/N): ');
      if (retry.toLowerCase() === 'y') {
        await this.gatherCredentials();
        await this.createEnvFile();
        await this.testConnection();
      } else {
        throw new Error('Setup aborted due to connection failure');
      }
    }
  }

  async showNextSteps() {
    console.log(chalk.green(`
🎉 Setup Complete!
==================

Your ClickUp Automation Toolkit is now configured and ready to use!

📋 What you can do now:

${chalk.cyan('Test the CLI:')}
  npm run cli test
  npm run cli config

${chalk.cyan('Create tasks instantly:')}
  npm run instant:feature "New Feature" "Feature description"
  npm run instant:bug "Bug Report" "Bug description"
  npm run instant:design "Design Task" "Design requirements"

${chalk.cyan('Use the CLI directly:')}
  ./bin/clickup-cli.js feature "Task Name" -d "Description"
  ./bin/clickup-cli.js bug "Bug Name" -d "Bug description"

${chalk.cyan('Programmatic usage:')}
  import ClickUpAutomation from './src/clickup-automation.js';
  const automation = new ClickUpAutomation();
  await automation.createTask('Task Name', 'Description');

📚 Documentation:
  - README.md - Complete usage guide
  - CONTRIBUTING.md - Development guide
  - docs/ - Additional documentation

🆘 Need help?
  - GitHub Issues: Report bugs or request features
  - GitHub Discussions: Ask questions and share ideas

Happy automating! 🚀
        `));

    const openDocs = await this.question('Would you like to open the README for more information? (y/N): ');
    if (openDocs.toLowerCase() === 'y') {
      const { exec } = await import('child_process');
      const readmePath = path.join(projectRoot, 'README.md');

      // Try to open with default system editor
      exec(`open "${readmePath}"`, (error) => {
        if (error) {
          console.log(chalk.blue('📖 Please check README.md for complete documentation'));
        } else {
          console.log(chalk.green('📖 Opening README.md...'));
        }
      });
    }
  }
}

// Run setup wizard if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  const wizard = new SetupWizard();
  wizard.run().catch(error => {
    console.error(chalk.red('💥 Setup failed:'), error.message);
    process.exit(1);
  });
}

export default SetupWizard;
